os: linux
dist: jammy
language: java
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/graalvm"
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
  # Check if GraalVM is already cached, if not download and install it
  - if [ ! -d "$HOME/graalvm/graalvm-community-openjdk-21.0.2+13.1" ]; then
    echo "GraalVM is not cached, installing...";
    wget https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz;
    mkdir -p $HOME/graalvm;
    tar -xzf graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz -C $HOME/graalvm;
    else
    echo "Using cached GraalVM";
    fi

  - export JAVA_HOME=$HOME/graalvm/graalvm-community-openjdk-21.0.2+13.1
  - export PATH=JAVA_HOME/bin:$PATH
script:
  - mvn clean install
