CREATE TABLE "USER"
(
    ID       IDENTITY NOT NULL PRIMARY KEY,
    USERNAME VARCHAR  NOT NULL UNIQUE,
    PASSWORD VARCHAR
);

CREATE TABLE AUTHORITY
(
    ID        IDENTITY NOT NULL PRIMARY KEY,
    AUTHORITY VARCHAR  NOT NULL,
    "USER"    INTEGER  NOT NULL,
    FOREIGN KEY ("USER") REFERENCES "USER" (ID)
);

CREATE TABLE FILE
(
    ID       IDENTITY NOT NULL PRIMARY KEY,
    BLOB_ID  VARCHAR UNIQUE,
    FILENAME VARCHAR,
    SIZE     BIGINT
);

CREATE TABLE VCF
(
    ID                 IDENTITY  NOT NULL PRIMARY KEY,
    FILE               INTEGER   NOT NULL UNIQUE,
    ASSEMBLY           ENUM ('GRCh37', 'GRCh38', 'T2T'),
    IS_PUBLIC          BOOLEAN   NOT NULL,
    CREATED_BY         INTEGER   NOT NULL,
    CREATION_DATE      TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY   INTEGER   NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL,
    FOREIGN KEY (FILE) REFERENCES FILE (ID),
    FOREIGN KEY (CREATED_BY) REFERENCES "USER" (ID),
    FOREIGN KEY (LAST_MODIFIED_BY) REFERENCES "USER" (ID)
);

CREATE TABLE VCF_SAMPLE
(
    ID      IDENTITY NOT NULL PRIMARY KEY,
    VCF     INTEGER  NOT NULL,
    VCF_KEY INTEGER  NOT NULL,
    NAME    VARCHAR  NOT NULL,
    FOREIGN KEY (VCF) REFERENCES VCF (ID),
    UNIQUE (VCF, VCF_KEY)
);

CREATE TABLE JOB
(
    ID                  IDENTITY                                           NOT NULL PRIMARY KEY,
    NAME                VARCHAR                                            NOT NULL,
    VCF                 INTEGER                                            NOT NULL,
    STATUS              ENUM ('COMPLETED', 'FAILED', 'PENDING', 'RUNNING') NOT NULL,
    SEQUENCING_METHOD   ENUM ('WES','WGS')                                 NOT NULL,
    ASSEMBLY            ENUM ('GRCh37', 'GRCh38', 'T2T')                   NOT NULL,
    VARIANT_FILTER_TREE INTEGER                                            NOT NULL,
    SAMPLE_FILTER_TREE  INTEGER                                            NOT NULL,
    IS_PUBLIC           BOOLEAN                                            NOT NULL,
    CREATED_BY          INTEGER                                            NOT NULL,
    CREATION_DATE       TIMESTAMP                                          NOT NULL,
    LAST_MODIFIED_BY    INTEGER                                            NOT NULL,
    LAST_MODIFIED_DATE  TIMESTAMP                                          NOT NULL,
    FOREIGN KEY (VCF) REFERENCES VCF (ID),
    FOREIGN KEY (CREATED_BY) REFERENCES "USER" (ID),
    FOREIGN KEY (LAST_MODIFIED_BY) REFERENCES "USER" (ID)
);

CREATE TABLE HPO_TERM
(
    ID   IDENTITY NOT NULL PRIMARY KEY,
    TERM VARCHAR  NOT NULL UNIQUE,
    NAME VARCHAR  NOT NULL
);

CREATE TABLE SAMPLE
(
    ID            IDENTITY                         NOT NULL PRIMARY KEY,
    JOB           INTEGER                          NOT NULL,
    JOB_KEY       INTEGER                          NOT NULL,
    INDIVIDUAL_ID VARCHAR                          NOT NULL,
    PATERNAL_ID   VARCHAR,
    MATERNAL_ID   VARCHAR,
    PROBAND       BOOLEAN                          NOT NULL,
    SEX           ENUM ('FEMALE','MALE','UNKNOWN') NOT NULL,
    AFFECTED      ENUM ('TRUE','FALSE','UNKNOWN')  NOT NULL,
    FOREIGN KEY (JOB) REFERENCES JOB (ID)
);

CREATE TABLE SAMPLE_HPO_TERM
(
    ID         IDENTITY NOT NULL PRIMARY KEY,
    SAMPLE     INTEGER  NOT NULL,
    SAMPLE_KEY INTEGER  NOT NULL,
    HPO_TERM   INTEGER  NOT NULL,
    FOREIGN KEY (SAMPLE) REFERENCES SAMPLE (ID),
    FOREIGN KEY (HPO_TERM) REFERENCES HPO_TERM (ID),
    UNIQUE (SAMPLE, SAMPLE_KEY),
    UNIQUE (SAMPLE, HPO_TERM)
);

CREATE TABLE REPORT
(
    ID   IDENTITY NOT NULL PRIMARY KEY,
    FILE INTEGER  NOT NULL UNIQUE,
    JOB  INTEGER  NOT NULL,
    FOREIGN KEY (FILE) REFERENCES FILE (ID),
    FOREIGN KEY (JOB) REFERENCES JOB (ID)
);

CREATE TABLE FILTER_TREE
(
    ID                 IDENTITY                  NOT NULL PRIMARY KEY,
    NAME               VARCHAR                   NOT NULL,
    DESCRIPTION        VARCHAR,
    FILE               INTEGER                   NOT NULL UNIQUE,
    TYPE               ENUM ('VARIANT','SAMPLE') NOT NULL,
    IS_PUBLIC          BOOLEAN                   NOT NULL,
    CREATED_BY         INTEGER                   NOT NULL,
    CREATION_DATE      TIMESTAMP                 NOT NULL,
    LAST_MODIFIED_BY   INTEGER                   NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP                 NOT NULL,
    FOREIGN KEY (FILE) REFERENCES FILE (ID),
    FOREIGN KEY (CREATED_BY) REFERENCES "USER" (ID),
    FOREIGN KEY (LAST_MODIFIED_BY) REFERENCES "USER" (ID)
);

CREATE TABLE FILTER_TREE_CLASS
(
    ID                IDENTITY NOT NULL PRIMARY KEY,
    NAME              VARCHAR  NOT NULL,
    DESCRIPTION       VARCHAR,
    IS_DEFAULT_FILTER BOOLEAN  NOT NULL,
    FILTER_TREE       INTEGER  NOT NULL,
    FILTER_TREE_KEY   INTEGER  NOT NULL,
    FOREIGN KEY (FILTER_TREE) REFERENCES FILTER_TREE (ID)
);

CREATE TABLE VARIANT_FILTER_CLASS
(
    ID                IDENTITY NOT NULL PRIMARY KEY,
    FILTER_TREE_CLASS INTEGER  NOT NULL,
    JOB               INTEGER  NOT NULL,
    FOREIGN KEY (FILTER_TREE_CLASS) REFERENCES FILTER_TREE_CLASS (ID),
    FOREIGN KEY (JOB) REFERENCES JOB (ID)
);

CREATE TABLE SAMPLE_FILTER_CLASS
(
    ID                IDENTITY NOT NULL PRIMARY KEY,
    FILTER_TREE_CLASS INTEGER  NOT NULL,
    JOB               INTEGER  NOT NULL,
    FOREIGN KEY (FILTER_TREE_CLASS) REFERENCES FILTER_TREE_CLASS (ID),
    FOREIGN KEY (JOB) REFERENCES JOB (ID)
);